version: '3.9'

services:
  transcendence:
    image: transcendence
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: transcendence
    networks:
      - transcendence
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    build: db
    container_name: postgres
    # restart: always
    networks:
      - transcendence
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data
    command: command

volumes:
  db:
    driver_opts:
      o: bind
      type: volume
      device: ${PWD}/postgres

networks:
  transcendence:
